server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
hu:
  vargyasb:
    tokenlib:
      keypaths:
        public: /Users/vargyasb/Downloads/public.pem