server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
spring:
  cloud:
    gateway:
      routes:
      - id: currency
        uri: lb://currency
        predicates:
        - Path=/currency/**
        filters:
        - RewritePath=/currency(?<segment>/?.*), /api$\{segment}
      - id: flights
        uri: lb://flights
        predicates:
        - Path=/flights/**
        filters:
        - RewritePath=/flights(?<segment>/?.*), /api$\{segment}
      - id: bonus
        uri: lb://bonus
        predicates:
        - Path=/bonus/**
        filters:
        - RewritePath=/bonus(?<segment>/?.*), /api$\{segment}