server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
hu:
  vargyasb:
    tokenlib:
      keypaths:
        private: /Users/vargyasb/Downloads/private.pem
        public: /Users/vargyasb/Downloads/public.pem